// Test: AWS Access Keys (should trigger AUTH_CREDENTIAL)
export const AWS_ACCESS_KEY_ID = "AKIAIOSFODNN7REAL1234";
export const AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYzREALKEY99";
export const AWS_SESSION_TOKEN = "ASIAIOSFODNN7SESS1234";
