// Test: RSA Private Key (should trigger AUTH_CREDENTIAL)
const PRIVATE_KEY = `-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEA0Z3VS5JJcds3xfn/yGaDAJJYLFqVx12m34BHPr3RkLhz2BOB
qKIBMQGPPdLrgsiMSj7PsNsGb5WQFOaH6NFaOJKQgrBS2z1bR1IU4BTrqBxZ1L+y
iN0P3JDg1Zpe9r02KQHRkaw5VlYuRguK8mLRJhDfePavNNPxBDfVhEOmXdHPx2gI
-----END RSA PRIVATE KEY-----`;
